// default categories and states fetch action types
export const CATEGORIES_STATES_LOADING = "CATEGORIES_STATES_LOADING"
export const CATEGORIES_STATES_FAIL = "CATEGORIES_STATES_FAIL"
export const CATEGORIES_STATES_SUCCESS = "CATEGORIES_STATES_SUCCESS"
//select filter or choose them
export const SELECT_CATEGORY = "SELECT_CATEGORY"

export const SELECT_STATE = "SELECT_STATE"
//business fetch types
export const BUSINESSES_FAIL = "BUSINESSES_FAIL"
export const BUSINESSES_SUCCESS = "BUSINESSES_SUCCESS"
export const BUSINESSES_LOADING = "BUSINESSES_LOADING"
export const SELECT_CATEGORY_AND_FETCH = "SELECT_CATEGORY_AND_FETCH"
export const SELECT_STATE_AND_FETCH = "SELECT_STATE_AND_FETCH"
//counts types
export const COUNTS_LOADING = "COUNTS_LOADING"
export const COUNTS_FAIL = "COUNTS_FAIL"
export const COUNTS_SUCCESS ="COUNTS_SUCCESS"

export const SET_MARKER_COORDINATES = "SET_MARKER_COORDINATES"

//set category search key and fetch categories
export const MATCHED_CATEGORIES_FAIL = "MATCHED_CATEGORIES_FAIL"
export const MATCHED_CATEGORIES_SUCCESS = "MATCHED_CATEGORIES_SUCCESS"
export const MATCHED_CATEGORIES_LOADING = "MATCHED_CATEGORIES_LOADING"

//set location search key and fetch locations
export const MATCHED_CITIES_FAIL = "MATCHED_CITIES_FAILL"
export const MATCHED_CITIES_SUCCESS = "MATCHED_CITIES_SUCCESS"
export const MATCHED_CITIES_LOADING = "MATCHED_CITIES_LOADING"

//PAGINATION
export const SET_PAGE_NUMBER = "SET_PAGE_NUMBER"
export const SET_CATEGORY_SEARCH_KEY = "SET_CATEGORY_SEARCH_KEY"

// set cities and get data
export const SET_CITY = "SET_CITY"
export const SET_ZIPCODE = "SET_ZIPCODE"
export const GET_ZIPCODES = "GET_ZIPCODES"
export const SET_BUSINESS_NAME = "SET_BUSINESS_NAME"




